global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'yc-monitoring-export'
    metrics_path: '/monitoring/v2/prometheusMetrics'
    params:
      folderId:
      - 'b1g7s2jj07pt6rc3i44m'
      service:
      - 'storage'
    bearer_token: 'AQVNzB2Sq-aRsjh88k5ciGnDTcAgm6c4JSBYieOE'
    static_configs:
    - targets: ['monitoring.api.cloud.yandex.net']
      labels:
          folderId: 'b1g7s2jj07pt6rc3i44m'
          service: 'storage'